### PR TITLE
Moved away from serverless/lib/plugins/aws to aws-sdk/clients/s3

### PR DESCRIPTION
**Pull request by nikordaris**
Updated the AWS client to use aws-sdk/client/s3 instead. Confirmed I was able to push a client/dist dir to my s3 bucket with serverless v1.4.0.

### CODE REVIEW

**Comment by shdpl** [comment]
@nharris85 Are you sure you're working on v1.4.0 and you have S.getServerlessPath defined?
It's not defined in my v1.4.0 tag.

**Comment by nikordaris** [comment]
@shdpl I double checked my version of serverless on the command line and it is v1.4.0. I am not getting the S.getServerlessPath not defined error. I created an example repo to show this working here:

[serverless-client-s3-example](https://github.com/nharris85/serverless-client-s3-example)

**Comment by kevzettler** [comment]
@nharris85 merge conflict here. I just merged #2 let me know if that was a bad move

**Comment by nikordaris** [comment]
Ah, ok I see what they are doing now. They are centralizing the list of approved providers into the core for consistency I suppose. @ar90n implemented it correctly for the frameworks convention. If it works with v1.4.0, @kevzettler can reject this pull request. I do still want to add the ability to set the stage and region as option arguments though. I can do that as a separate pull request.

**Comment by kevzettler** [comment]
@nharris85 I'm not readily setup to test this against v1.4.0. Looks like #2 was targeted at v1.0.3

> do still want to add the ability to set the stage and region as option arguments though. I can do that as a separate pull request.

I think this is valuable and I also think the version bump in package.json is needed:

https://github.com/kevzettler/serverless-client-s3/pull/3/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R41

Please do open up another PR with that and I will merge

**Pull request closed without merging**
